# Generated by Django 3.2.13 on 2022-05-28 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_boekenplank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='firstname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
