# Generated by Django 3.2.13 on 2022-05-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_boekenplank', '0002_author_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='lastname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
