# Generated by Django 4.0.4 on 2022-06-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_boekenplank', '0005_auto_20220528_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ManyToManyField(null=True, to='app_boekenplank.publisher'),
        ),
    ]
