# Generated by Django 4.0.4 on 2022-06-01 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_boekenplank', '0006_alter_book_publisher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookreview',
            old_name='title',
            new_name='name',
        ),
    ]
