# Generated by Django 4.0.4 on 2022-06-01 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_boekenplank', '0007_rename_title_bookreview_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreview',
            name='score',
        ),
    ]
