# Generated by Django 4.0.4 on 2022-06-01 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_boekenplank', '0008_remove_bookreview_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookreview',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookreview',
            name='user',
        ),
    ]
