# Generated by Django 4.0.4 on 2022-06-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_boekenplank', '0011_bookreview_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
