# Generated by Django 4.0.4 on 2022-06-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_boekenplank', '0012_book_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='bookreview',
            name='name',
        ),
        migrations.AddField(
            model_name='bookreview',
            name='reviewText',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
