# Generated by Django 4.0.4 on 2022-06-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_boekenplank', '0013_rename_name_book_title_remove_bookreview_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='score',
            field=models.IntegerField(choices=[(0, 'BAD'), (1, 'NORMAL'), (2, 'GOOD')], null=True),
        ),
    ]
