# Generated by Django 4.0.4 on 2022-06-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_boekenplank', '0014_bookreview_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='score',
            field=models.IntegerField(choices=[(0, 1), (1, 'NORMAL'), (2, 'GOOD')], null=True),
        ),
    ]
