# Generated by Django 4.0.4 on 2022-06-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_boekenplank', '0015_alter_bookreview_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='score',
            field=models.IntegerField(choices=[(1, 'TERRIBLE'), (2, 'BAD'), (3, 3)], null=True),
        ),
    ]
