# Generated by Django 4.0.4 on 2022-06-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_boekenplank', '0016_alter_bookreview_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='score',
            field=models.IntegerField(choices=[(1, 'TERRIBLE'), (2, 'BAD'), (3, 'OK'), (4, 'GOOD'), (5, 'GREAT'), (6, 'EXCELLENT')], null=True),
        ),
    ]
