# Generated by Django 4.0.4 on 2022-06-16 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_boekenplank', '0017_alter_bookreview_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='book',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app_boekenplank.book'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='score',
            field=models.IntegerField(choices=[(1, 'TERRIBLE'), (2, 'BAD'), (3, 'OK'), (4, 'GOOD'), (5, 'GREAT'), (6, 'EXCELLENT')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='title',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
