# Generated by Django 4.0.4 on 2022-06-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_boekenplank', '0018_alter_bookreview_book_alter_bookreview_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ManyToManyField(to='app_boekenplank.publisher'),
        ),
    ]
