# Generated by Django 4.0.4 on 2022-06-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_boekenplank', '0019_alter_book_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='book_images'),
        ),
    ]
