# Generated by Django 4.0.4 on 2022-06-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_boekenplank', '0021_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='', upload_to='book_images'),
            preserve_default=False,
        ),
    ]
