# Generated by Django 4.0.4 on 2022-06-17 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_boekenplank', '0022_alter_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='image',
            new_name='image2',
        ),
    ]
