# Generated by Django 4.0.4 on 2022-06-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_boekenplank', '0023_rename_image_book_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image3',
            field=models.ImageField(default='', upload_to='book_images'),
            preserve_default=False,
        ),
    ]
