# Generated by Django 4.0.4 on 2022-06-17 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_boekenplank', '0024_book_image3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='image2',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='book',
            name='image3',
        ),
    ]
