# Generated by Django 4.0.4 on 2022-06-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_boekenplank', '0025_rename_image2_book_image_remove_book_image3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ManyToManyField(to='app_boekenplank.category')),
            ],
        ),
    ]
