# Generated by Django 4.0.4 on 2022-07-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_boekenplank', '0027_author_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
