# Generated by Django 3.2.21 on 2023-10-05 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_boekenplank', '0032_commanddislike_commandlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandlike',
            name='comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='command_likes', to='app_boekenplank.reviewcomment'),
        ),
    ]
